name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install valgrind
    - uses: actions/checkout@v2
    - name: build
      run: make
    - name: test
      run: make test
